first_join_spawn:
  enabled: true
  world: world
  x: 0
  y: 100
  z: 0
  yaw: 0
  pitch: 0

first_join_commands:
  enabled: true
  commands:
    - 'lp user %player_name% parent settrack gamerank rank0'
    - 'give %player_name% minecraft:stone 1'

health_scale:
  enabled: true
  value: 20

spawner_tweaks:
  ##must restart to toggle this feature
  disable_spawner_mob_item_drops: true

mob_tweaks:
  endermites_immune_to_lightning: true

disabled_recipes: []
  ##must restart to edit this feature
#  - SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE
#  - VEX_ARMOR_TRIM_SMITHING_TEMPLATE
#  - WILD_ARMOR_TRIM_SMITHING_TEMPLATE
#  - COAST_ARMOR_TRIM_SMITHING_TEMPLATE
#  - DUNE_ARMOR_TRIM_SMITHING_TEMPLATE
#  - WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE
#  - RAISER_ARMOR_TRIM_SMITHING_TEMPLATE
#  - SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE
#  - HOST_ARMOR_TRIM_SMITHING_TEMPLATE
#  - WARD_ARMOR_TRIM_SMITHING_TEMPLATE
#  - SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE
#  - TIDE_ARMOR_TRIM_SMITHING_TEMPLATE
#  - SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE
#  - RIB_ARMOR_TRIM_SMITHING_TEMPLATE
#  - EYE_ARMOR_TRIM_SMITHING_TEMPLATE
#  - SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE
#  - FLOW_ARMOR_TRIM_SMITHING_TEMPLATE
#  - BOLT_ARMOR_TRIM_SMITHING_TEMPLATE

cooldowns:
  death_message_cooldown_seconds: 30

general_messages:
  no_permission: '<red>You do not have permission to do that!'
  must_specify_player: '<red>You must specify a player!'
  player_not_found: '<red>Player not found!'
  incorrect_usage: '<red>Usage: <white><usage>'

seen_messages:
  seen_offline_message: '<green><target> was last seen <time> ago!'
  seen_never_joined_message: '<green><target> has never been seen before!'
  seen_online_message: '<green><target> has been online for <time>!'

spawner_messages:
  no_silk_warning_message: '<red>You must sneak to break a spawner without silk touch'
  spawner_name: '<gray><entitytype> Spawner'

feed_messages:
  feed_message: '<green>Your hunger has been refilled!'
  feed_all_message: '<green>Everyone''s hunger has been refilled!'
  feed_other_message: '<green>You have refilled <target>''s hunger!'
  feed_fed_by_other_message: '<green>Your hunger has been refilled by <source>!'

flyspeed_messages:
  flyspeed_reset_message: '<green>Your fly speed has been reset to default!'
  flyspeed_invalid_speed_message: '<red>Invalid speed! Must be between 0.1 and 10!'
  flyspeed_set_message: '<green>Your fly speed has been set to <speed>!'

heal_messages:
  heal_message: '<green>You have been healed!'
  heal_all_message: '<green>Everyone has been healed!'
  heal_other_message: '<green>You have healed <target>!'
  heal_heal_by_other_message: '<green>You were healed by <source>!'

itemname_messages:
  itemname_no_item_message: '<red>You must be holding an item to rename it!'
  itemname_message: '<green>Your item has been renamed to <name>!'

near_messages:
  near_no_players_message: '<red>No players found within <radius> blocks!'
  near_near_players_message: '<green>Players within <radius> blocks:'
  near_nearby_players_message: '<green><player> is <distance> blocks away.'
  near_invalid_radius_message: '<red>Invalid radius! Must be a number!'

ping_messages:
  ping_message: '<green>Your ping is <ping>ms!'
  ping_other_message: '<green><target>''s ping is <ping>ms!'

ptime_messages:
  ptime_reset_message: '<green>Your time has been reset to default!'
  ptime_set_message: '<green> Your time has been set to <time>!'
  ptime_invalid_time_message: '<red>Invalid time!'

pweather_messages:
  pweather_reset_message: '<green>Your weather has been reset to default!'
  pweather_set_message: '<green>Your weather has been set to <weather>!'
  pweather_invalid_weather_message: '<red>Invalid weather!'

repair_messages:
  repair_no_item_message: '<red>You must be holding an item to repair it!'
  repair_invalid_item_message: '<red>Invalid item!'
  repair_message: '<green>Your item has been repaired!'
  repair_all_message: '<green>All of your items have been repaired!'

top_messages:
  top_message: '<green>Teleported to the top!'

bottom_messages:
  bottom_message: '<green>Teleported to the bottom!'
  bottom_message_invalid_block: '<red>No block found below you!'

god_messages:
  god_enabled_message: '<green>God mode enabled!'
  god_disabled_message: '<red>God mode disabled!'

afk_title_feature:
  afk_placeholder: '%xantiafk_status%'
  afk_titles:
    - '<red>You are AFK'
    - '<red>COME BACK!'
  afk_subtitles:
    - '<gray>The quick brown fox jumps over the lazy dog'
    - '<gray>Look at this dude, standing there, all AFK'

death_messages:
  suffix:
    - ' <gray>while fleeing '

  killed_by_player:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>was slain by <killer> <gray>using <weapon><gray>.'
  shot_by_player:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>was shot by <killer> <gray>using <weapon><gray>.'
  shot_by_entity:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>was shot by <killer><gray>.'
  shot:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>was shot.'
  killed_by_entity:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>was slain by <killer><gray>.'

  block_explosion:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>exploded<suffix>.'
  campfire:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>was roasted in a campfire<suffix>.'
  contact:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>was pricked to death<suffix>.'
  cramming:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>was squished<suffix>.'
  custom:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>died<suffix>.'
  dragon_breath:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>inhaled dragon breath<suffix>.'
  drowning:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>drowned<suffix>.'
  entity_explosion:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>was blown up<suffix>.'
  fall:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>fell from a high place<suffix>.'
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>couldn''t fly<suffix>.'
  falling_block:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>was squashed by a falling block<suffix>.'
  fire:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>went up in flames<suffix>.'
  fire_tick:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>burned to death<suffix>.'
  fly_into_wall:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>experienced kinetic energy<suffix>.'
  freeze:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>froze to death<suffix>.'
  hot_floor:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>discovered the floor was lava<suffix>.'
  kill:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>was killed<suffix>.'
  lava:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>tried to swim in lava<suffix>.'
  lightning:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>was struck by lightning<suffix>.'
  magic:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>was killed by magic<suffix>.'
  poison:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>was poisoned to death<suffix>.'
  sonic_boom:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>was sonically boomed<suffix>.'
  starvation:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>starved to death<suffix>.'
  suffocation:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>suffocated in a wall<suffix>.'
  suicide:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>died<suffix>.'
  thorns:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>was killed by thorns<suffix>.'
  void:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>fell out of the world<suffix>.'
  wither:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>withered away<suffix>.'
  world_border:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>left the confines of this world<suffix>.'
  default:
    - '<white>[<red>ðŸ’€<white>] <deceased> <gray>died<suffix>.'
